# Site settings
title: Taoyi(Jasper) Chen
description: 'Personal Website'
url: 'https://github.com/JasperChen-us/JasperChen-us.github.io'
baseurl: ''
profilepic: '/images/personal photo.jpg'
bkimage: '/images/background.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/js/all.min.js'


author:
  name: 'Jasper Chen'
  email: jasperch@umich.edu
#  mastodon: tzuehlke@mstdn.social
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  JasperChen-us
  linkedin_username:  taoyi-chen
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-sitemap

exclude: ['README.md', 'screenshot-overview.png']
